### ISSUE TITLE
Usage of tf.contrib.distributions.percentile fails

### ISSUE THREAD

**Issue by martinstuder** [databricks/tensorframes#129]
Consider the following dummy example using `tf.contrib.distributions.percentile`:
```
from pyspark.context import SparkContext
from pyspark.conf import SparkConf
import tensorflow as tf
import tensorframes as tfs
from pyspark import SQLContext
from pyspark.sql import Row
from pyspark.sql.functions import *

conf = SparkConf().setAppName("repro")
sc = SparkContext(conf=conf)
sqlContext = SQLContext(sc)

data = [Row(x=[1.111, 0.516, 12.759]), Row(x=[2.222, 1.516, 13.759]), Row(x=[3.333, 2.516, 14.759]), Row(x=[4.444, 3.516, 15.759])]
df = tfs.analyze(sqlContext.createDataFrame(data))

with tf.Graph().as_default() as g:
	x = tfs.block(df, "x")
	q = tf.constant(90, 'float64', name='Percentile')
	qntl = tf.contrib.distributions.percentile(x, q, axis=1)
	result = tfs.map_blocks(x, df)
	
```
This fails with 
```
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2752, in _as_graph_element_locked
    return op.outputs[out_n]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 5, in <module>
  File "/tmp/spark-7f93e8f4-b6dc-4356-98fc-4c6de58c1e71/userFiles-f204b475-06b5-44e9-9a11-dbee001767d4/databricks_tensorframes-0.2.9-s_2.11.jar/tensorframes/core.py", line 312, in map_blocks
  File "/tmp/spark-7f93e8f4-b6dc-4356-98fc-4c6de58c1e71/userFiles-f204b475-06b5-44e9-9a11-dbee001767d4/databricks_tensorframes-0.2.9-s_2.11.jar/tensorframes/core.py", line 152, in _map
  File "/tmp/spark-7f93e8f4-b6dc-4356-98fc-4c6de58c1e71/userFiles-f204b475-06b5-44e9-9a11-dbee001767d4/databricks_tensorframes-0.2.9-s_2.11.jar/tensorframes/core.py", line 83, in _add_shapes
  File "/usr/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2880, in get_tensor_by_name
    return self.as_graph_element(name, allow_tensor=True, allow_operation=False)
  File "/usr/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2708, in as_graph_element
    return self._as_graph_element_locked(obj, allow_tensor, allow_operation)
  File "/usr/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2757, in _as_graph_element_locked
    % (repr(name), repr(op_name), len(op.outputs)))
KeyError: "The name 'percentile/assert_integer/statically_determined_was_integer:0' refers to a Tensor which does not exist. The operation, 'percentile/assert_integer/statically_determined_was_integer', exists but only has 0 outputs."
```

**Comment by thunterdb** [comment]
Hello Martin, thank you for the report. Can you tell me which version of tensorflow, spark and python you are using?

**Comment by martinstuder** [comment]
Hi Tim,
this is with Spark 2.2.0 and TensorFlow 1.3. Leaving out `axis = 1` in the call to to `tf.contrib.distributions.percentile` works. In the doc of `tf.contrib.distributions.percentile` it says: "If axis is not None, x must have statically known number of dimensions.". I guess that would be violated for the number of rows as they would not be known when processing by blocks. Given that, I don't actually think this is a tensorframes issue ...

**Comment by thunterdb** [comment]
Thanks Martin. If this is not an issue then, I will close this issue.
