### ISSUE TITLE
How many times install(include) Tesorframe in my Spark cluster?

### ISSUE THREAD

**Issue by SungMinHong** [databricks/tensorframes#133]
Hi, Tensorframe is interesting to me. So I want to test  Tensorframe in my Spark's cluster. But I have wonder.
I wondering that Tensorframe just needs to install to master node and don't needs to install any worker.

-I have 1 cluster that has 3 nodes ( 1 master, 2  worker)

I would be grateful if you could please answer my question.

**Comment by SungMinHong** [comment]
I solved that problem. I just missing python script file name in the command.  : (

"spark-submit --packages databricks:tensorframes:0.2.9-s_2.11 <python_script_name>"

**Comment by SungMinHong** [comment]
Spark YARN cluster is not serving Virtulenv until now.

**Comment by shinalone** [comment]
> Hi, Everyone. Tensorframe is interesting to me. So I want to test Tensorframe in my Spark's cluster. But I have wonder.
> 
> 1. I wondering that Tensorframe just needs to install to master node and don't needs to install any worker.
> 2. This command is okay that "pyspark --packages databricks:tensorframes:0.2.9-s_2.11"
>    But I want to use Spark's cluster. So, I want to use this command "spark-submit --packages databricks:tensorframes:0.2.9-s_2.11". But this command has the error like this:
> 
> ```
> Exception in thread "main" java.lang.IllegalArgumentException: Missing application resource.
>        at org.apache.spark.launcher.CommandBuilderUtils.checkArgument(CommandBuilderUtils.java:241)
>        at org.apache.spark.launcher.SparkSubmitCommandBuilder.buildSparkSubmitArgs(SparkSubmitCommandBuilder.java:160)
>        at org.apache.spark.launcher.SparkSubmitCommandBuilder.buildSparkSubmitCommand(SparkSubmitCommandBuilder.java:274)
>        at org.apache.spark.launcher.SparkSubmitCommandBuilder.buildCommand(SparkSubmitCommandBuilder.java:151)
>        at org.apache.spark.launcher.Main.main(Main.java:86)
> ```
> 
> Someone have this error?
> 
> * I have Spark's cluster that has 3 nodes (YARN on a Hadoop cluster, 1 master, 2  worker)
> * I used Virtualenv for Tensorflow(CPU version)
> * I install panda-0.20.3
> 
> I would be grateful if you could please answer my question.

@SungMinHong Same question!
