### ISSUE TITLE
 java.lang.ClassNotFoundException: org.tensorframes.impl.DebugRowOps

### ISSUE THREAD

**Issue by jq** [databricks/tensorframes#49]
I build the jar by follow the readme,
and then run it in pycharm 
https://www.dropbox.com/s/qmrs72l0p8p4bc2/Screen%20Shot%202016-07-06%20at%2011.40.26%20PM.png?dl=0
I add the self build jar as content root, I guess that's cause the error, 

line 11 is     x = tfs.block(df, "x")

code:

```
import tensorflow as tf
import tensorframes as tfs
from pyspark.shell import sqlContext
from pyspark.sql import Row

data = [Row(x=float(x)) for x in range(10)]
df = sqlContext.createDataFrame(data)

with tf.Graph().as_default() as g:
    # The TensorFlow placeholder that corresponds to column 'x'.
    # The shape of the placeholder is automatically inferred from the DataFrame.
    x = tfs.block(df, "x")
    # The output that adds 3 to x
    z = tf.add(x, 3, name='z')
    # The resulting dataframe
    df2 = tfs.map_blocks(z, df)

# The transform is lazy as for most DataFrame operations. This will trigger it:
df2.collect()
```

log

```
Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
16/07/06 23:28:43 INFO SparkContext: Running Spark version 1.6.1
16/07/06 23:28:44 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
16/07/06 23:28:44 INFO SecurityManager: Changing view acls to: julian_qian
16/07/06 23:28:44 INFO SecurityManager: Changing modify acls to: julian_qian
16/07/06 23:28:44 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users with view permissions: Set(julian_qian); users with modify permissions: Set(julian_qian)
16/07/06 23:28:44 INFO Utils: Successfully started service 'sparkDriver' on port 60597.
16/07/06 23:28:45 INFO Slf4jLogger: Slf4jLogger started
16/07/06 23:28:45 INFO Remoting: Starting remoting
16/07/06 23:28:45 INFO Remoting: Remoting started; listening on addresses :[akka.tcp://sparkDriverActorSystem@10.63.21.172:60598]
16/07/06 23:28:45 INFO Utils: Successfully started service 'sparkDriverActorSystem' on port 60598.
16/07/06 23:28:45 INFO SparkEnv: Registering MapOutputTracker
16/07/06 23:28:45 INFO SparkEnv: Registering BlockManagerMaster
16/07/06 23:28:45 INFO DiskBlockManager: Created local directory at /private/var/folders/9c/h8czn5n53yd69xz45wjhk0fw0000gn/T/blockmgr-5174cef3-29d9-4d2a-a84e-279a0e3d2f83
16/07/06 23:28:45 INFO MemoryStore: MemoryStore started with capacity 511.1 MB
16/07/06 23:28:45 INFO SparkEnv: Registering OutputCommitCoordinator
16/07/06 23:28:45 WARN Utils: Service 'SparkUI' could not bind on port 4040. Attempting port 4041.
16/07/06 23:28:45 INFO Utils: Successfully started service 'SparkUI' on port 4041.
16/07/06 23:28:45 INFO SparkUI: Started SparkUI at http://10.63.21.172:4041
16/07/06 23:28:45 INFO Executor: Starting executor ID driver on host localhost
16/07/06 23:28:45 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 60599.
16/07/06 23:28:45 INFO NettyBlockTransferService: Server created on 60599
16/07/06 23:28:45 INFO BlockManagerMaster: Trying to register BlockManager
16/07/06 23:28:45 INFO BlockManagerMasterEndpoint: Registering block manager localhost:60599 with 511.1 MB RAM, BlockManagerId(driver, localhost, 60599)
16/07/06 23:28:45 INFO BlockManagerMaster: Registered BlockManager
Welcome to
      ____              __
     / __/__  ___ _____/ /__
    _\ \/ _ \/ _ `/ __/  '_/
   /__ / .__/\_,_/_/ /_/\_\   version 1.6.1
      /_/

Using Python version 2.7.10 (default, Dec  1 2015 20:00:13)
SparkContext available as sc, HiveContext available as sqlContext.
16/07/06 23:28:46 INFO HiveContext: Initializing execution hive, version 1.2.1
16/07/06 23:28:46 INFO ClientWrapper: Inspected Hadoop version: 2.6.0
16/07/06 23:28:46 INFO ClientWrapper: Loaded org.apache.hadoop.hive.shims.Hadoop23Shims for Hadoop version 2.6.0
16/07/06 23:28:46 INFO HiveMetaStore: 0: Opening raw store with implemenation class:org.apache.hadoop.hive.metastore.ObjectStore
16/07/06 23:28:46 INFO ObjectStore: ObjectStore, initialize called
16/07/06 23:28:46 INFO Persistence: Property hive.metastore.integral.jdo.pushdown unknown - will be ignored
16/07/06 23:28:46 INFO Persistence: Property datanucleus.cache.level2 unknown - will be ignored
16/07/06 23:28:46 WARN Connection: BoneCP specified but not present in CLASSPATH (or one of dependencies)
16/07/06 23:28:47 WARN Connection: BoneCP specified but not present in CLASSPATH (or one of dependencies)
16/07/06 23:28:48 INFO ObjectStore: Setting MetaStore object pin classes with hive.metastore.cache.pinobjtypes="Table,StorageDescriptor,SerDeInfo,Partition,Database,Type,FieldSchema,Order"
16/07/06 23:28:48 INFO Datastore: The class "org.apache.hadoop.hive.metastore.model.MFieldSchema" is tagged as "embedded-only" so does not have its own datastore table.
16/07/06 23:28:48 INFO Datastore: The class "org.apache.hadoop.hive.metastore.model.MOrder" is tagged as "embedded-only" so does not have its own datastore table.
16/07/06 23:28:49 INFO Datastore: The class "org.apache.hadoop.hive.metastore.model.MFieldSchema" is tagged as "embedded-only" so does not have its own datastore table.
16/07/06 23:28:49 INFO Datastore: The class "org.apache.hadoop.hive.metastore.model.MOrder" is tagged as "embedded-only" so does not have its own datastore table.
16/07/06 23:28:49 INFO MetaStoreDirectSql: Using direct SQL, underlying DB is DERBY
16/07/06 23:28:49 INFO ObjectStore: Initialized ObjectStore
16/07/06 23:28:49 WARN ObjectStore: Version information not found in metastore. hive.metastore.schema.verification is not enabled so recording the schema version 1.2.0
16/07/06 23:28:49 WARN ObjectStore: Failed to get database default, returning NoSuchObjectException
16/07/06 23:28:49 INFO HiveMetaStore: Added admin role in metastore
16/07/06 23:28:49 INFO HiveMetaStore: Added public role in metastore
16/07/06 23:28:49 INFO HiveMetaStore: No user is added in admin role, since config is empty
16/07/06 23:28:49 INFO HiveMetaStore: 0: get_all_databases
16/07/06 23:28:49 INFO audit: ugi=julian_qian   ip=unknown-ip-addr  cmd=get_all_databases   
16/07/06 23:28:49 INFO HiveMetaStore: 0: get_functions: db=default pat=*
16/07/06 23:28:49 INFO audit: ugi=julian_qian   ip=unknown-ip-addr  cmd=get_functions: db=default pat=* 
16/07/06 23:28:49 INFO Datastore: The class "org.apache.hadoop.hive.metastore.model.MResourceUri" is tagged as "embedded-only" so does not have its own datastore table.
16/07/06 23:28:49 INFO SessionState: Created HDFS directory: /tmp/hive/julian_qian
16/07/06 23:28:49 INFO SessionState: Created local directory: /var/folders/9c/h8czn5n53yd69xz45wjhk0fw0000gn/T/julian_qian
16/07/06 23:28:49 INFO SessionState: Created local directory: /var/folders/9c/h8czn5n53yd69xz45wjhk0fw0000gn/T/f9d3c8e6-6b5d-4a0c-b2cf-a50aa101fb62_resources
16/07/06 23:28:49 INFO SessionState: Created HDFS directory: /tmp/hive/julian_qian/f9d3c8e6-6b5d-4a0c-b2cf-a50aa101fb62
16/07/06 23:28:49 INFO SessionState: Created local directory: /var/folders/9c/h8czn5n53yd69xz45wjhk0fw0000gn/T/julian_qian/f9d3c8e6-6b5d-4a0c-b2cf-a50aa101fb62
16/07/06 23:28:49 INFO SessionState: Created HDFS directory: /tmp/hive/julian_qian/f9d3c8e6-6b5d-4a0c-b2cf-a50aa101fb62/_tmp_space.db
16/07/06 23:28:49 INFO HiveContext: default warehouse location is /user/hive/warehouse
16/07/06 23:28:49 INFO HiveContext: Initializing HiveMetastoreConnection version 1.2.1 using Spark classes.
16/07/06 23:28:49 INFO ClientWrapper: Inspected Hadoop version: 2.6.0
16/07/06 23:28:49 INFO ClientWrapper: Loaded org.apache.hadoop.hive.shims.Hadoop23Shims for Hadoop version 2.6.0
16/07/06 23:28:50 INFO HiveMetaStore: 0: Opening raw store with implemenation class:org.apache.hadoop.hive.metastore.ObjectStore
16/07/06 23:28:50 INFO ObjectStore: ObjectStore, initialize called
16/07/06 23:28:50 INFO Persistence: Property hive.metastore.integral.jdo.pushdown unknown - will be ignored
16/07/06 23:28:50 INFO Persistence: Property datanucleus.cache.level2 unknown - will be ignored
16/07/06 23:28:50 WARN Connection: BoneCP specified but not present in CLASSPATH (or one of dependencies)
16/07/06 23:28:50 WARN Connection: BoneCP specified but not present in CLASSPATH (or one of dependencies)
16/07/06 23:28:51 INFO ObjectStore: Setting MetaStore object pin classes with hive.metastore.cache.pinobjtypes="Table,StorageDescriptor,SerDeInfo,Partition,Database,Type,FieldSchema,Order"
16/07/06 23:28:51 INFO Datastore: The class "org.apache.hadoop.hive.metastore.model.MFieldSchema" is tagged as "embedded-only" so does not have its own datastore table.
16/07/06 23:28:51 INFO Datastore: The class "org.apache.hadoop.hive.metastore.model.MOrder" is tagged as "embedded-only" so does not have its own datastore table.
16/07/06 23:28:52 INFO Datastore: The class "org.apache.hadoop.hive.metastore.model.MFieldSchema" is tagged as "embedded-only" so does not have its own datastore table.
16/07/06 23:28:52 INFO Datastore: The class "org.apache.hadoop.hive.metastore.model.MOrder" is tagged as "embedded-only" so does not have its own datastore table.
16/07/06 23:28:52 INFO MetaStoreDirectSql: Using direct SQL, underlying DB is DERBY
16/07/06 23:28:52 INFO ObjectStore: Initialized ObjectStore
16/07/06 23:28:52 WARN ObjectStore: Version information not found in metastore. hive.metastore.schema.verification is not enabled so recording the schema version 1.2.0
16/07/06 23:28:52 WARN ObjectStore: Failed to get database default, returning NoSuchObjectException
16/07/06 23:28:52 INFO HiveMetaStore: Added admin role in metastore
16/07/06 23:28:52 INFO HiveMetaStore: Added public role in metastore
16/07/06 23:28:52 INFO HiveMetaStore: No user is added in admin role, since config is empty
16/07/06 23:28:52 INFO HiveMetaStore: 0: get_all_databases
16/07/06 23:28:52 INFO audit: ugi=julian_qian   ip=unknown-ip-addr  cmd=get_all_databases   
16/07/06 23:28:53 INFO HiveMetaStore: 0: get_functions: db=default pat=*
16/07/06 23:28:53 INFO audit: ugi=julian_qian   ip=unknown-ip-addr  cmd=get_functions: db=default pat=* 
16/07/06 23:28:53 INFO Datastore: The class "org.apache.hadoop.hive.metastore.model.MResourceUri" is tagged as "embedded-only" so does not have its own datastore table.
16/07/06 23:28:53 INFO SessionState: Created local directory: /var/folders/9c/h8czn5n53yd69xz45wjhk0fw0000gn/T/77eb618d-61cc-470e-abb4-18d356833efb_resources
16/07/06 23:28:53 INFO SessionState: Created HDFS directory: /tmp/hive/julian_qian/77eb618d-61cc-470e-abb4-18d356833efb
16/07/06 23:28:53 INFO SessionState: Created local directory: /var/folders/9c/h8czn5n53yd69xz45wjhk0fw0000gn/T/julian_qian/77eb618d-61cc-470e-abb4-18d356833efb
16/07/06 23:28:53 INFO SessionState: Created HDFS directory: /tmp/hive/julian_qian/77eb618d-61cc-470e-abb4-18d356833efb/_tmp_space.db
```

error log:

```
Traceback (most recent call last):
  File "/Users/julian_qian/PycharmProjects/tensorflow/tfs.py", line 11, in <module>
    x = tfs.block(df, "x")
  File "/Users/julian_qian/etc/work/python/tensorframes/tensorframes-assembly-0.2.3.jar/tensorframes/core.py", line 315, in block
  File "/Users/julian_qian/etc/work/python/tensorframes/tensorframes-assembly-0.2.3.jar/tensorframes/core.py", line 333, in _auto_placeholder
  File "/Users/julian_qian/etc/work/python/tensorframes/tensorframes-assembly-0.2.3.jar/tensorframes/core.py", line 30, in _java_api
  File "/usr/local/Cellar/apache-spark/1.6.1/libexec/python/lib/py4j-0.9-src.zip/py4j/java_gateway.py", line 813, in __call__
  File "/usr/local/Cellar/apache-spark/1.6.1/libexec/python/lib/pyspark.zip/pyspark/sql/utils.py", line 45, in deco
  File "/usr/local/Cellar/apache-spark/1.6.1/libexec/python/lib/py4j-0.9-src.zip/py4j/protocol.py", line 308, in get_return_value
py4j.protocol.Py4JJavaError: An error occurred while calling o32.loadClass.
: java.lang.ClassNotFoundException: org.tensorframes.impl.DebugRowOps
    at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:231)
    at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:381)
    at py4j.Gateway.invoke(Gateway.java:259)
    at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:133)
    at py4j.commands.CallCommand.execute(CallCommand.java:79)
    at py4j.GatewayConnection.run(GatewayConnection.java:209)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by thunterdb** [comment]
It looks like the jar file that you built may not be loaded into the Spark java virtual machine.
 - are you able to run some spark command?
 - can you access the content of the tensorframes jar?

I do not have much insight into what pyspark is doing, so you may be better off for now using spark directly with ipython or jupyter.

**Comment by thunterdb** [comment]
@jq I published a new version of tensorframes so you should not have to build it yourself. Let me know if it helps.

**Comment by jq** [comment]
Thanks! will give it a try!

**Comment by mhamilton723** [comment]
I am having this same problem and I just built tensorframes

**Comment by mhamilton723** [comment]
@thunterdb I have tried using the pre-built tensorframes on the spark plugin website and I have tried building my own version of tensorframes. Only my built version can get this far before it encounters this error. Have you figured out what is going on? Thanks

**Comment by thunterdb** [comment]
This may be a bit tricky since it depends on how pycharm caches jars. If someone else uses pycharm, they should comment as well.

**Comment by jeroenvlek** [comment]
I'm also facing this issue. I built the master (42c7fb2) and got stuck here. Using Jupyter, Python 3.5 and Spark 2.0.0  (2.11).

"PYSPARK_SUBMIT_ARGS": "--master yarn --deploy-mode --jars /opt/tensorframes/tensorframes-assembly-0.2.4.jar --client pyspark-shell"

Py4JJavaError: An error occurred while calling o56.loadClass.
: java.lang.ClassNotFoundException: org.tensorframes.impl.DebugRowOps

**Comment by thunterdb** [comment]
@jeroenvlek I finally got some time to build a new release. Can you try to use the published release candidate?

**Comment by thunterdb** [comment]
I believe this issue should be addressed now with the new release. I am going to close this issue, but feel free to reopen it if it does not work.

**Comment by llfice** [comment]
I am also having this same problem and I just built tensorframes

**Comment by ronitshaw** [comment]
I'm getting the following error as well! 
```
Py4JJavaError                             Traceback (most recent call last)
<ipython-input-36-17e37754773e> in <module>()
     23 # Create transformer and apply it to our input data
     24 transformer = KerasTransformer(inputCol="features", outputCol="predictions", modelFile=model_path)
---> 25 final_df = transformer.transform(input_df)

/Users/ronit_ibm/anaconda3/lib/python3.6/site-packages/pyspark/ml/base.py in transform(self, dataset, params)
    171                 return self.copy(params)._transform(dataset)
    172             else:
--> 173                 return self._transform(dataset)
    174         else:
    175             raise ValueError("Params must be a param map but got %s." % type(params))

/Users/ronit_ibm/Documents/temp_simple_moedel/spark-deep-learning-1.5.0/target/scala-2.11/spark-deep-learning-assembly-1.5.0-spark2.4.jar/sparkdl/transformers/keras_tensor.py in _transform(self, dataset)
     63                                     inputMapping={self.getInputCol(): inputTensorName},
     64                                     outputMapping={outputTensorName: self.getOutputCol()})
---> 65         return transformer.transform(dataset)

/Users/ronit_ibm/anaconda3/lib/python3.6/site-packages/pyspark/ml/base.py in transform(self, dataset, params)
    171                 return self.copy(params)._transform(dataset)
    172             else:
--> 173                 return self._transform(dataset)
    174         else:
    175             raise ValueError("Params must be a param map but got %s." % type(params))

/Users/ronit_ibm/Documents/temp_simple_moedel/spark-deep-learning-1.5.0/target/scala-2.11/spark-deep-learning-assembly-1.5.0-spark2.4.jar/sparkdl/transformers/tf_tensor.py in _transform(self, dataset)
    104         graph = tf.Graph()
    105         with tf.Session(graph=graph):
--> 106             analyzed_df = tfs.analyze(dataset)
    107             out_tnsr_op_names = [tfx.op_name(tnsr_name) for tnsr_name, _ in output_mapping]
    108             # Load graph

/Users/ronit_ibm/Documents/temp_simple_moedel/spark-deep-learning-1.5.0/target/scala-2.11/spark-deep-learning-assembly-1.5.0-spark2.4.jar/tensorframes/core.py in analyze(dframe)
    377     :return: a Spark DataFrame with metadata information embedded.
    378     """
--> 379     return DataFrame(_java_api().analyze(dframe._jdf), _sql)
    380 
    381 def append_shape(dframe, col, shape):

/Users/ronit_ibm/Documents/temp_simple_moedel/spark-deep-learning-1.5.0/target/scala-2.11/spark-deep-learning-assembly-1.5.0-spark2.4.jar/tensorframes/core.py in _java_api()
     33     # You cannot simply call the creation of the the class on the _jvm due to classloader issues
     34     # with Py4J.
---> 35     return _jvm.Thread.currentThread().getContextClassLoader().loadClass(javaClassName) \
     36         .newInstance()
     37 

/Users/ronit_ibm/anaconda3/lib/python3.6/site-packages/py4j/java_gateway.py in __call__(self, *args)
   1255         answer = self.gateway_client.send_command(command)
   1256         return_value = get_return_value(
-> 1257             answer, self.gateway_client, self.target_id, self.name)
   1258 
   1259         for temp_arg in temp_args:

/Users/ronit_ibm/anaconda3/lib/python3.6/site-packages/pyspark/sql/utils.py in deco(*a, **kw)
     61     def deco(*a, **kw):
     62         try:
---> 63             return f(*a, **kw)
     64         except py4j.protocol.Py4JJavaError as e:
     65             s = e.java_exception.toString()

/Users/ronit_ibm/anaconda3/lib/python3.6/site-packages/py4j/protocol.py in get_return_value(answer, gateway_client, target_id, name)
    326                 raise Py4JJavaError(
    327                     "An error occurred while calling {0}{1}{2}.\n".
--> 328                     format(target_id, ".", name), value)
    329             else:
    330                 raise Py4JError(

Py4JJavaError: An error occurred while calling o96.loadClass.
: java.lang.ClassNotFoundException: org.tensorframes.impl.DebugRowOps
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by louismartin** [comment]
Still having this issue, any help?

**Comment by dbkerkela** [comment]
I think this was deprecated?
