### ISSUE TITLE
Couldn't run the example

### ISSUE THREAD

**Issue by Jeongseob** [databricks/tensorframes#63]
Hi All,

I am trying to use TensorFrames. While I am running the [python example](https://github.com/databricks/tensorframes#how-to-run-in-python), I am facing the error like below.

```
Traceback (most recent call last):
  File "/home_bunch/jeahn/projects/spark-examples/test_tensorframes.py", line 18, in <module>
    df2 = tfs.map_blocks(z, df)
  File "/home/jeahn/.ivy2/jars/databricks_tensorframes-0.2.3-s_2.10.jar/tensorframes/core.py", line 217, in map_blocks
  File "/cm/shared/apps/spark/spark-1.6.1-bin-without-hadoop/python/lib/py4j-0.9-src.zip/py4j/java_gateway.py", line 813, in __call__
  File "/cm/shared/apps/spark/spark-1.6.1-bin-without-hadoop/python/lib/pyspark.zip/pyspark/sql/utils.py", line 45, in deco
  File "/cm/shared/apps/spark/spark-1.6.1-bin-without-hadoop/python/lib/py4j-0.9-src.zip/py4j/protocol.py", line 308, in get_return_value
py4j.protocol.Py4JJavaError: An error occurred while calling o77.buildDF.
: java.lang.UnsatisfiedLinkError: no jnitensorflow in java.library.path
        at java.lang.ClassLoader.loadLibrary(Unknown Source)
        at java.lang.Runtime.loadLibrary0(Unknown Source)
        at java.lang.System.loadLibrary(Unknown Source)
        at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:654)
        at org.bytedeco.javacpp.Loader.load(Loader.java:492)
        at org.bytedeco.javacpp.Loader.load(Loader.java:409)
        at org.bytedeco.javacpp.tensorflow.<clinit>(tensorflow.java:10)
        at org.tensorframes.impl.TensorFlowOps$._init$lzycompute(TensorFlowOps.scala:21)
        at org.tensorframes.impl.TensorFlowOps$._init(TensorFlowOps.scala:19)
        at org.tensorframes.impl.TensorFlowOps$.initTensorFlow(TensorFlowOps.scala:27)
        at org.tensorframes.impl.TensorFlowOps$.analyzeGraph(TensorFlowOps.scala:85)
        at org.tensorframes.impl.DebugRowOps.mapBlocks(DebugRowOps.scala:307)
        at org.tensorframes.impl.DebugRowOps.mapBlocks(DebugRowOps.scala:290)
        at org.tensorframes.impl.PythonOpBuilder.buildDF(PythonInterface.scala:126)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:231)
        at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:381)
        at py4j.Gateway.invoke(Gateway.java:259)
        at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:133)
        at py4j.commands.CallCommand.execute(CallCommand.java:79)
        at py4j.GatewayConnection.run(GatewayConnection.java:209)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.UnsatisfiedLinkError: /tmp/javacpp3334753250106708/libjnitensorflow.so: libcudart.so.7.5: cannot open shared object file: No such file or directory
        at java.lang.ClassLoader$NativeLibrary.load(Native Method)
        at java.lang.ClassLoader.loadLibrary0(Unknown Source)
        at java.lang.ClassLoader.loadLibrary(Unknown Source)
        at java.lang.Runtime.load0(Unknown Source)
        at java.lang.System.load(Unknown Source)
        at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:637)
        ... 21 more
```

It seems like that the TensorFlow built in the system should have GPU-enabled version. I am wondering the python example assumes that GPU-enabled TensorFlow or not. Actually, my system does not have any GPU. 

If not, does anyone experience the same issue? I am currently using Spark 1.6 and Tensorflow r0.12.

Thanks,
Jeongseob

**Comment by thunterdb** [comment]
@Jeongseob I published a new version `0.2.6-rc1`, which should solve this problem for CPU-only configurations. Let me know if you still hit this issue. Also, I would advise you to upgrade to spark 2.x. TensorFrames has to use some developer APIs that may have changed since Spark 1.6.

**Comment by ronitshaw** [comment]
I'm still facing this issue! Any leads/fix on the above?
